version: '3.9'
services:
  chrome:
    image: 'selenium/standalone-chrome'

  awslocal:
    image: localstack/localstack
    environment:
      HOSTNAME_EXTERNAL: awslocal
      SERVICES: 'cloudformation,s3,sqs'
      DISABLE_CORS_CHECKS: 1
      EXTRA_CORS_ALLOWED_HEADERS: x-requested-with

  webserver:
    image: "${WEBSERVER_IMAGE}"
    depends_on:
      - laravel
    environment:
      UPSTREAM_HOST: laravel

  mail:
    image: axllent/mailpit:latest

  laravel:
    image: "${LARAVEL_IMAGE}"
    depends_on:
      - cache
      - chrome

  cache:
    image: redis:alpine
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
